"""initial_capacity_connect_schema

Revision ID: 0a5d11c45adc
Revises: 
Create Date: 2026-09-09 08:55:34.637466
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a5d11c45adc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cc_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_cc_interest_name')
    )
    op.create_index(op.f('ix_cc_interest_name'), 'cc_interest', ['name'], unique=False)
    op.create_table('cc_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_cc_skill_name')
    )
    op.create_index('ix_cc_skill_category', 'cc_skill', ['category'], unique=False)
    op.create_index(op.f('ix_cc_skill_name'), 'cc_skill', ['name'], unique=False)
    op.create_table('cc_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_salt', sa.String(length=64), nullable=False),
    sa.Column('password_algorithm', sa.String(length=32), nullable=False),
    sa.Column('password_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('approval_status', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('avatar_seed', sa.String(length=64), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_cc_user_email')
    )
    op.create_index(op.f('ix_cc_user_approval_status'), 'cc_user', ['approval_status'], unique=False)
    op.create_index(op.f('ix_cc_user_email'), 'cc_user', ['email'], unique=False)
    op.create_index(op.f('ix_cc_user_role'), 'cc_user', ['role'], unique=False)
    op.create_index('ix_cc_user_role_status', 'cc_user', ['role', 'approval_status'], unique=False)
    op.create_table('cc_approval_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requested_role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cc_approval_request_status'), 'cc_approval_request', ['status'], unique=False)
    op.create_index(op.f('ix_cc_approval_request_user_id'), 'cc_approval_request', ['user_id'], unique=False)
    op.create_index('ix_cc_approval_status_created', 'cc_approval_request', ['status', 'created_at'], unique=False)
    op.create_table('cc_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('enrollment_deadline', sa.Date(), nullable=True),
    sa.Column('banner_url', sa.String(length=400), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_cc_course_code')
    )
    op.create_index(op.f('ix_cc_course_category'), 'cc_course', ['category'], unique=False)
    op.create_index(op.f('ix_cc_course_code'), 'cc_course', ['code'], unique=False)
    op.create_index(op.f('ix_cc_course_status'), 'cc_course', ['status'], unique=False)
    op.create_index('ix_cc_course_status_start', 'cc_course', ['status', 'start_date'], unique=False)
    op.create_index(op.f('ix_cc_course_title'), 'cc_course', ['title'], unique=False)
    op.create_table('cc_password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_cc_reset_token_hash')
    )
    op.create_index(op.f('ix_cc_password_reset_token_user_id'), 'cc_password_reset_token', ['user_id'], unique=False)
    op.create_index('ix_cc_reset_user_active', 'cc_password_reset_token', ['user_id', 'used_at'], unique=False)
    op.create_table('cc_qualification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=160), nullable=False),
    sa.Column('field_of_study', sa.String(length=160), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=40), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cc_qualification_user_id'), 'cc_qualification', ['user_id'], unique=False)
    op.create_index('ix_cc_qualification_user_year', 'cc_qualification', ['user_id', 'end_year'], unique=False)
    op.create_table('cc_trainee_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('organization', sa.String(length=160), nullable=False),
    sa.Column('employee_code', sa.String(length=64), nullable=False),
    sa.Column('station', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('total_experience_years', sa.Float(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('career_goal', sa.Text(), nullable=False),
    sa.Column('profile_completion', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_cc_trainee_profile_user')
    )
    op.create_index(op.f('ix_cc_trainee_profile_user_id'), 'cc_trainee_profile', ['user_id'], unique=False)
    op.create_table('cc_trainer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('organization', sa.String(length=160), nullable=False),
    sa.Column('specialization', sa.String(length=200), nullable=False),
    sa.Column('years_of_training', sa.Float(), nullable=False),
    sa.Column('highest_qualification', sa.String(length=160), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('languages', sa.String(length=200), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('rating_average', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('profile_completion', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_cc_trainer_profile_user')
    )
    op.create_index(op.f('ix_cc_trainer_profile_user_id'), 'cc_trainer_profile', ['user_id'], unique=False)
    op.create_table('cc_user_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['cc_interest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'interest_id', name='uq_cc_user_interest')
    )
    op.create_index(op.f('ix_cc_user_interest_interest_id'), 'cc_user_interest', ['interest_id'], unique=False)
    op.create_index(op.f('ix_cc_user_interest_user_id'), 'cc_user_interest', ['user_id'], unique=False)
    op.create_table('cc_user_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('proficiency_score', sa.Integer(), nullable=False),
    sa.Column('years_of_practice', sa.Float(), nullable=False),
    sa.Column('is_teachable', sa.Boolean(), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('proficiency_score >= 0 AND proficiency_score <= 100', name='ck_cc_user_skill_score'),
    sa.ForeignKeyConstraint(['skill_id'], ['cc_skill.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_cc_user_skill')
    )
    op.create_index(op.f('ix_cc_user_skill_skill_id'), 'cc_user_skill', ['skill_id'], unique=False)
    op.create_index('ix_cc_user_skill_skill_level', 'cc_user_skill', ['skill_id', 'level'], unique=False)
    op.create_index(op.f('ix_cc_user_skill_user_id'), 'cc_user_skill', ['user_id'], unique=False)
    op.create_table('cc_work_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('role_title', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cc_experience_user_start', 'cc_work_experience', ['user_id', 'start_date'], unique=False)
    op.create_index(op.f('ix_cc_work_experience_user_id'), 'cc_work_experience', ['user_id'], unique=False)
    op.create_table('cc_announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cc_announcement_audience'), 'cc_announcement', ['audience'], unique=False)
    op.create_index('ix_cc_announcement_pub_audience', 'cc_announcement', ['published_at', 'audience'], unique=False)
    op.create_table('cc_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('passing_marks', sa.Float(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cc_assessment_course_id'), 'cc_assessment', ['course_id'], unique=False)
    op.create_index('ix_cc_assessment_course_status', 'cc_assessment', ['course_id', 'status'], unique=False)
    op.create_table('cc_certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_number', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=8), nullable=False),
    sa.Column('verification_code', sa.String(length=64), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainee_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number', name='uq_cc_certificate_number'),
    sa.UniqueConstraint('course_id', 'trainee_id', name='uq_cc_certificate_course_trainee')
    )
    op.create_index(op.f('ix_cc_certificate_certificate_number'), 'cc_certificate', ['certificate_number'], unique=False)
    op.create_index(op.f('ix_cc_certificate_course_id'), 'cc_certificate', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_certificate_trainee_id'), 'cc_certificate', ['trainee_id'], unique=False)
    op.create_index(op.f('ix_cc_certificate_verification_code'), 'cc_certificate', ['verification_code'], unique=False)
    op.create_table('cc_course_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('content_rating', sa.Integer(), nullable=False),
    sa.Column('trainer_rating', sa.Integer(), nullable=False),
    sa.Column('relevance_rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('overall_rating >= 1 AND overall_rating <= 5', name='ck_cc_feedback_rating'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainee_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'trainee_id', name='uq_cc_feedback_course_trainee')
    )
    op.create_index(op.f('ix_cc_course_feedback_course_id'), 'cc_course_feedback', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_course_feedback_trainee_id'), 'cc_course_feedback', ['trainee_id'], unique=False)
    op.create_table('cc_course_required_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('minimum_level', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.CheckConstraint('weight >= 0 AND weight <= 10', name='ck_cc_course_skill_weight'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['cc_skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'skill_id', name='uq_cc_course_skill')
    )
    op.create_index(op.f('ix_cc_course_required_skill_course_id'), 'cc_course_required_skill', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_course_required_skill_skill_id'), 'cc_course_required_skill', ['skill_id'], unique=False)
    op.create_table('cc_course_trainer_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('assignment_role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'trainer_id', name='uq_cc_course_trainer')
    )
    op.create_index('ix_cc_assignment_trainer_status', 'cc_course_trainer_assignment', ['trainer_id', 'status'], unique=False)
    op.create_index(op.f('ix_cc_course_trainer_assignment_course_id'), 'cc_course_trainer_assignment', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_course_trainer_assignment_trainer_id'), 'cc_course_trainer_assignment', ['trainer_id'], unique=False)
    op.create_table('cc_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainee_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'trainee_id', name='uq_cc_enrollment')
    )
    op.create_index(op.f('ix_cc_enrollment_course_id'), 'cc_enrollment', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_enrollment_status'), 'cc_enrollment', ['status'], unique=False)
    op.create_index(op.f('ix_cc_enrollment_trainee_id'), 'cc_enrollment', ['trainee_id'], unique=False)
    op.create_index('ix_cc_enrollment_trainee_status', 'cc_enrollment', ['trainee_id', 'status'], unique=False)
    op.create_table('cc_learning_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=16), nullable=False),
    sa.Column('module_name', sa.String(length=160), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('external_url', sa.String(length=500), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cc_learning_resource_course_id'), 'cc_learning_resource', ['course_id'], unique=False)
    op.create_index('ix_cc_resource_course_order', 'cc_learning_resource', ['course_id', 'sort_order'], unique=False)
    op.create_table('cc_assessment_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['cc_assessment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainee_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'trainee_id', 'attempt_number', name='uq_cc_attempt_number')
    )
    op.create_index(op.f('ix_cc_assessment_attempt_assessment_id'), 'cc_assessment_attempt', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_cc_assessment_attempt_trainee_id'), 'cc_assessment_attempt', ['trainee_id'], unique=False)
    op.create_index('ix_cc_attempt_trainee_status', 'cc_assessment_attempt', ['trainee_id', 'status'], unique=False)
    op.create_table('cc_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_multi_select', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['cc_assessment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['cc_skill.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cc_question_assessment_id'), 'cc_question', ['assessment_id'], unique=False)
    op.create_index('ix_cc_question_assessment_order', 'cc_question', ['assessment_id', 'sort_order'], unique=False)
    op.create_table('cc_resource_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['cc_enrollment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['cc_learning_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'resource_id', name='uq_cc_resource_progress')
    )
    op.create_index(op.f('ix_cc_resource_progress_enrollment_id'), 'cc_resource_progress', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_cc_resource_progress_resource_id'), 'cc_resource_progress', ['resource_id'], unique=False)
    op.create_table('cc_assessment_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('unanswered_count', sa.Integer(), nullable=False),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('grade', sa.String(length=8), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['cc_assessment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attempt_id'], ['cc_assessment_attempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainee_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', name='uq_cc_result_attempt')
    )
    op.create_index(op.f('ix_cc_assessment_result_assessment_id'), 'cc_assessment_result', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_cc_assessment_result_attempt_id'), 'cc_assessment_result', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_cc_assessment_result_trainee_id'), 'cc_assessment_result', ['trainee_id'], unique=False)
    op.create_index('ix_cc_result_trainee_passed', 'cc_assessment_result', ['trainee_id', 'is_passed'], unique=False)
    op.create_table('cc_question_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['cc_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cc_option_question_order', 'cc_question_option', ['question_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_cc_question_option_question_id'), 'cc_question_option', ['question_id'], unique=False)
    op.create_table('cc_attempt_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('marks_awarded', sa.Float(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['cc_assessment_attempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['cc_question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['cc_question_option.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', 'selected_option_id', name='uq_cc_attempt_answer')
    )
    op.create_index(op.f('ix_cc_attempt_answer_attempt_id'), 'cc_attempt_answer', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_cc_attempt_answer_question_id'), 'cc_attempt_answer', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cc_attempt_answer_question_id'), table_name='cc_attempt_answer')
    op.drop_index(op.f('ix_cc_attempt_answer_attempt_id'), table_name='cc_attempt_answer')
    op.drop_table('cc_attempt_answer')
    op.drop_index(op.f('ix_cc_question_option_question_id'), table_name='cc_question_option')
    op.drop_index('ix_cc_option_question_order', table_name='cc_question_option')
    op.drop_table('cc_question_option')
    op.drop_index('ix_cc_result_trainee_passed', table_name='cc_assessment_result')
    op.drop_index(op.f('ix_cc_assessment_result_trainee_id'), table_name='cc_assessment_result')
    op.drop_index(op.f('ix_cc_assessment_result_attempt_id'), table_name='cc_assessment_result')
    op.drop_index(op.f('ix_cc_assessment_result_assessment_id'), table_name='cc_assessment_result')
    op.drop_table('cc_assessment_result')
    op.drop_index(op.f('ix_cc_resource_progress_resource_id'), table_name='cc_resource_progress')
    op.drop_index(op.f('ix_cc_resource_progress_enrollment_id'), table_name='cc_resource_progress')
    op.drop_table('cc_resource_progress')
    op.drop_index('ix_cc_question_assessment_order', table_name='cc_question')
    op.drop_index(op.f('ix_cc_question_assessment_id'), table_name='cc_question')
    op.drop_table('cc_question')
    op.drop_index('ix_cc_attempt_trainee_status', table_name='cc_assessment_attempt')
    op.drop_index(op.f('ix_cc_assessment_attempt_trainee_id'), table_name='cc_assessment_attempt')
    op.drop_index(op.f('ix_cc_assessment_attempt_assessment_id'), table_name='cc_assessment_attempt')
    op.drop_table('cc_assessment_attempt')
    op.drop_index('ix_cc_resource_course_order', table_name='cc_learning_resource')
    op.drop_index(op.f('ix_cc_learning_resource_course_id'), table_name='cc_learning_resource')
    op.drop_table('cc_learning_resource')
    op.drop_index('ix_cc_enrollment_trainee_status', table_name='cc_enrollment')
    op.drop_index(op.f('ix_cc_enrollment_trainee_id'), table_name='cc_enrollment')
    op.drop_index(op.f('ix_cc_enrollment_status'), table_name='cc_enrollment')
    op.drop_index(op.f('ix_cc_enrollment_course_id'), table_name='cc_enrollment')
    op.drop_table('cc_enrollment')
    op.drop_index(op.f('ix_cc_course_trainer_assignment_trainer_id'), table_name='cc_course_trainer_assignment')
    op.drop_index(op.f('ix_cc_course_trainer_assignment_course_id'), table_name='cc_course_trainer_assignment')
    op.drop_index('ix_cc_assignment_trainer_status', table_name='cc_course_trainer_assignment')
    op.drop_table('cc_course_trainer_assignment')
    op.drop_index(op.f('ix_cc_course_required_skill_skill_id'), table_name='cc_course_required_skill')
    op.drop_index(op.f('ix_cc_course_required_skill_course_id'), table_name='cc_course_required_skill')
    op.drop_table('cc_course_required_skill')
    op.drop_index(op.f('ix_cc_course_feedback_trainee_id'), table_name='cc_course_feedback')
    op.drop_index(op.f('ix_cc_course_feedback_course_id'), table_name='cc_course_feedback')
    op.drop_table('cc_course_feedback')
    op.drop_index(op.f('ix_cc_certificate_verification_code'), table_name='cc_certificate')
    op.drop_index(op.f('ix_cc_certificate_trainee_id'), table_name='cc_certificate')
    op.drop_index(op.f('ix_cc_certificate_course_id'), table_name='cc_certificate')
    op.drop_index(op.f('ix_cc_certificate_certificate_number'), table_name='cc_certificate')
    op.drop_table('cc_certificate')
    op.drop_index('ix_cc_assessment_course_status', table_name='cc_assessment')
    op.drop_index(op.f('ix_cc_assessment_course_id'), table_name='cc_assessment')
    op.drop_table('cc_assessment')
    op.drop_index('ix_cc_announcement_pub_audience', table_name='cc_announcement')
    op.drop_index(op.f('ix_cc_announcement_audience'), table_name='cc_announcement')
    op.drop_table('cc_announcement')
    op.drop_index(op.f('ix_cc_work_experience_user_id'), table_name='cc_work_experience')
    op.drop_index('ix_cc_experience_user_start', table_name='cc_work_experience')
    op.drop_table('cc_work_experience')
    op.drop_index(op.f('ix_cc_user_skill_user_id'), table_name='cc_user_skill')
    op.drop_index('ix_cc_user_skill_skill_level', table_name='cc_user_skill')
    op.drop_index(op.f('ix_cc_user_skill_skill_id'), table_name='cc_user_skill')
    op.drop_table('cc_user_skill')
    op.drop_index(op.f('ix_cc_user_interest_user_id'), table_name='cc_user_interest')
    op.drop_index(op.f('ix_cc_user_interest_interest_id'), table_name='cc_user_interest')
    op.drop_table('cc_user_interest')
    op.drop_index(op.f('ix_cc_trainer_profile_user_id'), table_name='cc_trainer_profile')
    op.drop_table('cc_trainer_profile')
    op.drop_index(op.f('ix_cc_trainee_profile_user_id'), table_name='cc_trainee_profile')
    op.drop_table('cc_trainee_profile')
    op.drop_index('ix_cc_qualification_user_year', table_name='cc_qualification')
    op.drop_index(op.f('ix_cc_qualification_user_id'), table_name='cc_qualification')
    op.drop_table('cc_qualification')
    op.drop_index('ix_cc_reset_user_active', table_name='cc_password_reset_token')
    op.drop_index(op.f('ix_cc_password_reset_token_user_id'), table_name='cc_password_reset_token')
    op.drop_table('cc_password_reset_token')
    op.drop_index(op.f('ix_cc_course_title'), table_name='cc_course')
    op.drop_index('ix_cc_course_status_start', table_name='cc_course')
    op.drop_index(op.f('ix_cc_course_status'), table_name='cc_course')
    op.drop_index(op.f('ix_cc_course_code'), table_name='cc_course')
    op.drop_index(op.f('ix_cc_course_category'), table_name='cc_course')
    op.drop_table('cc_course')
    op.drop_index('ix_cc_approval_status_created', table_name='cc_approval_request')
    op.drop_index(op.f('ix_cc_approval_request_user_id'), table_name='cc_approval_request')
    op.drop_index(op.f('ix_cc_approval_request_status'), table_name='cc_approval_request')
    op.drop_table('cc_approval_request')
    op.drop_index('ix_cc_user_role_status', table_name='cc_user')
    op.drop_index(op.f('ix_cc_user_role'), table_name='cc_user')
    op.drop_index(op.f('ix_cc_user_email'), table_name='cc_user')
    op.drop_index(op.f('ix_cc_user_approval_status'), table_name='cc_user')
    op.drop_table('cc_user')
    op.drop_index(op.f('ix_cc_skill_name'), table_name='cc_skill')
    op.drop_index('ix_cc_skill_category', table_name='cc_skill')
    op.drop_table('cc_skill')
    op.drop_index(op.f('ix_cc_interest_name'), table_name='cc_interest')
    op.drop_table('cc_interest')
    # ### end Alembic commands ###
