"""add_competency_intelligence_schema

Revision ID: 2a0a622797dd
Revises: f1521489770b
Create Date: 2026-09-17 19:01:15.477414
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a0a622797dd'
down_revision: Union[str, Sequence[str], None] = 'f1521489770b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cc_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cc_organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_cc_organization_name'), 'cc_organization', ['name'], unique=False)
    op.create_table('cc_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_cc_subject_name'), 'cc_subject', ['name'], unique=False)
    op.create_table('cc_capacity_ai_conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_cc_ai_conversation_status'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cc_ai_conversation_user_time', 'cc_capacity_ai_conversation', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_cc_capacity_ai_conversation_user_id'), 'cc_capacity_ai_conversation', ['user_id'], unique=False)
    op.create_table('cc_competency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scale_version', sa.String(length=24), server_default='sih26075_v1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scale_version = 'sih26075_v1'", name='ck_cc_competency_scale'),
    sa.ForeignKeyConstraint(['subject_id'], ['cc_subject.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    comment='Scale v1: 1 Awareness; 2 Basic (guided); 3 Working (independent); 4 Advanced (complex work); 5 Expert (mentors others).'
    )
    op.create_index(op.f('ix_cc_competency_is_active'), 'cc_competency', ['is_active'], unique=False)
    op.create_index(op.f('ix_cc_competency_subject_id'), 'cc_competency', ['subject_id'], unique=False)
    op.create_table('cc_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['cc_organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_cc_department_org'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_cc_department_code')
    )
    op.create_index(op.f('ix_cc_department_organization_id'), 'cc_department', ['organization_id'], unique=False)
    op.create_table('cc_organizational_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['cc_organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_cc_org_role_org'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_cc_org_role_code')
    )
    op.create_index(op.f('ix_cc_organizational_role_organization_id'), 'cc_organizational_role', ['organization_id'], unique=False)
    op.create_table('cc_trainer_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('timezone_name', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'unavailable', 'tentative')", name='ck_cc_availability_status'),
    sa.CheckConstraint('ends_at > starts_at', name='ck_cc_availability_window'),
    sa.ForeignKeyConstraint(['trainer_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_id', 'starts_at', 'ends_at', name='uq_cc_trainer_availability_window')
    )
    op.create_index('ix_cc_availability_trainer_window', 'cc_trainer_availability', ['trainer_id', 'starts_at', 'ends_at'], unique=False)
    op.create_index(op.f('ix_cc_trainer_availability_trainer_id'), 'cc_trainer_availability', ['trainer_id'], unique=False)
    op.create_table('cc_trainer_capacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_hours', sa.Float(), nullable=False),
    sa.Column('allocated_hours', sa.Float(), nullable=False),
    sa.Column('max_courses', sa.Integer(), nullable=False),
    sa.Column('allocated_courses', sa.Integer(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('allocated_participants', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='ck_cc_capacity_period'),
    sa.CheckConstraint('max_hours >= 0 AND allocated_hours >= 0 AND allocated_hours <= max_hours AND max_courses >= 0 AND allocated_courses >= 0 AND allocated_courses <= max_courses AND max_participants >= 0 AND allocated_participants >= 0 AND allocated_participants <= max_participants', name='ck_cc_capacity_nonnegative'),
    sa.ForeignKeyConstraint(['trainer_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_id', 'starts_at', 'ends_at', name='uq_cc_trainer_capacity_period')
    )
    op.create_index('ix_cc_capacity_trainer_period', 'cc_trainer_capacity', ['trainer_id', 'starts_at', 'ends_at'], unique=False)
    op.create_index(op.f('ix_cc_trainer_capacity_trainer_id'), 'cc_trainer_capacity', ['trainer_id'], unique=False)
    op.create_table('cc_trainer_fit_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('policy_code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('competency_weight', sa.Float(), nullable=False),
    sa.Column('experience_weight', sa.Float(), nullable=False),
    sa.Column('effectiveness_weight', sa.Float(), nullable=False),
    sa.Column('availability_weight', sa.Float(), nullable=False),
    sa.Column('capacity_weight', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('abs(competency_weight + experience_weight + effectiveness_weight + availability_weight + capacity_weight - 100) < 0.000001', name='ck_cc_fit_weight_sum'),
    sa.CheckConstraint('competency_weight BETWEEN 0 AND 100 AND experience_weight BETWEEN 0 AND 100 AND effectiveness_weight BETWEEN 0 AND 100 AND availability_weight BETWEEN 0 AND 100 AND capacity_weight BETWEEN 0 AND 100', name='ck_cc_fit_weight_ranges'),
    sa.CheckConstraint('version >= 1', name='ck_cc_fit_policy_version'),
    sa.ForeignKeyConstraint(['organization_id'], ['cc_organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'competency_weight', 'experience_weight', 'effectiveness_weight', 'availability_weight', 'capacity_weight', name='uq_cc_fit_policy_values'),
    sa.UniqueConstraint('policy_code', 'version', name='uq_cc_fit_policy_version')
    )
    op.create_index(op.f('ix_cc_trainer_fit_weights_organization_id'), 'cc_trainer_fit_weights', ['organization_id'], unique=False)
    op.create_table('cc_training_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'completed', 'archived')", name='ck_cc_program_status'),
    sa.CheckConstraint('ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at', name='ck_cc_program_period'),
    sa.ForeignKeyConstraint(['organization_id'], ['cc_organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_cc_training_program_organization_id'), 'cc_training_program', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cc_training_program_status'), 'cc_training_program', ['status'], unique=False)
    op.create_table('cc_course_competency_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('requirement_type', sa.String(length=16), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("requirement_type IN ('prerequisite', 'outcome', 'trainer')", name='ck_cc_course_comp_type'),
    sa.CheckConstraint('required_level BETWEEN 1 AND 5', name='ck_cc_course_comp_level'),
    sa.CheckConstraint('weight BETWEEN 0 AND 100', name='ck_cc_course_comp_weight'),
    sa.ForeignKeyConstraint(['competency_id'], ['cc_competency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'competency_id', 'requirement_type', name='uq_cc_course_comp_req')
    )
    op.create_index(op.f('ix_cc_course_competency_requirement_competency_id'), 'cc_course_competency_requirement', ['competency_id'], unique=False)
    op.create_index(op.f('ix_cc_course_competency_requirement_course_id'), 'cc_course_competency_requirement', ['course_id'], unique=False)
    op.create_table('cc_course_module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_cc_module_status'),
    sa.CheckConstraint('position >= 1 AND duration_minutes >= 0', name='ck_cc_module_numbers'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'position', name='uq_cc_module_order')
    )
    op.create_index(op.f('ix_cc_course_module_course_id'), 'cc_course_module', ['course_id'], unique=False)
    op.create_table('cc_learning_path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'completed', 'archived')", name='ck_cc_path_status'),
    sa.ForeignKeyConstraint(['program_id'], ['cc_training_program.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', name='uq_cc_learning_path_user')
    )
    op.create_index(op.f('ix_cc_learning_path_program_id'), 'cc_learning_path', ['program_id'], unique=False)
    op.create_index(op.f('ix_cc_learning_path_user_id'), 'cc_learning_path', ['user_id'], unique=False)
    op.create_index('ix_cc_path_user_status', 'cc_learning_path', ['user_id', 'status'], unique=False)
    op.create_table('cc_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(audience = 'user' AND user_id IS NOT NULL) OR (audience <> 'user' AND user_id IS NULL)", name='ck_cc_notification_user_target'),
    sa.CheckConstraint("audience <> 'course' OR course_id IS NOT NULL", name='ck_cc_notification_course_target'),
    sa.CheckConstraint("audience <> 'organization' OR organization_id IS NOT NULL", name='ck_cc_notification_org_target'),
    sa.CheckConstraint("audience IN ('all', 'trainees', 'trainers', 'admins', 'user', 'course', 'organization')", name='ck_cc_notification_audience'),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_cc_notification_status'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['cc_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cc_notification_course_id'), 'cc_notification', ['course_id'], unique=False)
    op.create_index('ix_cc_notification_feed', 'cc_notification', ['audience', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_cc_notification_organization_id'), 'cc_notification', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cc_notification_user_id'), 'cc_notification', ['user_id'], unique=False)
    op.create_table('cc_organizational_capacity_need',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('population_count', sa.Integer(), nullable=False),
    sa.Column('demand_count', sa.Integer(), nullable=False),
    sa.Column('population_context', sa.Text(), nullable=False),
    sa.Column('demand_context', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'fulfilled', 'archived')", name='ck_cc_need_status'),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name='ck_cc_need_period'),
    sa.CheckConstraint('population_count >= 0 AND demand_count >= 0 AND demand_count <= population_count', name='ck_cc_need_population'),
    sa.CheckConstraint('required_level BETWEEN 1 AND 5', name='ck_cc_need_level'),
    sa.ForeignKeyConstraint(['competency_id'], ['cc_competency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id', 'organization_id'], ['cc_department.id', 'cc_department.organization_id'], name='fk_cc_need_department', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['cc_organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_cc_capacity_need_code')
    )
    op.create_index('ix_cc_need_org_status', 'cc_organizational_capacity_need', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_cc_organizational_capacity_need_competency_id'), 'cc_organizational_capacity_need', ['competency_id'], unique=False)
    op.create_index(op.f('ix_cc_organizational_capacity_need_department_id'), 'cc_organizational_capacity_need', ['department_id'], unique=False)
    op.create_index(op.f('ix_cc_organizational_capacity_need_organization_id'), 'cc_organizational_capacity_need', ['organization_id'], unique=False)
    op.create_table('cc_trainer_fit_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('weights_id', sa.Integer(), nullable=False),
    sa.Column('eligibility_status', sa.String(length=24), nullable=False),
    sa.Column('competency_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('effectiveness_score', sa.Float(), nullable=False),
    sa.Column('availability_score', sa.Float(), nullable=False),
    sa.Column('capacity_score', sa.Float(), nullable=False),
    sa.Column('competency_weight', sa.Float(), nullable=False),
    sa.Column('experience_weight', sa.Float(), nullable=False),
    sa.Column('effectiveness_weight', sa.Float(), nullable=False),
    sa.Column('availability_weight', sa.Float(), nullable=False),
    sa.Column('capacity_weight', sa.Float(), nullable=False),
    sa.Column('weighted_total', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=64), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("eligibility_status IN ('eligible', 'ineligible', 'insufficient_evidence')", name='ck_cc_fit_eligibility'),
    sa.CheckConstraint('abs(weighted_total - (competency_score * competency_weight + experience_score * experience_weight + effectiveness_score * effectiveness_weight + availability_score * availability_weight + capacity_score * capacity_weight) / 100.0) < 0.0001', name='ck_cc_fit_weighted_total'),
    sa.CheckConstraint('competency_score BETWEEN 0 AND 100 AND experience_score BETWEEN 0 AND 100 AND effectiveness_score BETWEEN 0 AND 100 AND availability_score BETWEEN 0 AND 100 AND capacity_score BETWEEN 0 AND 100 AND weighted_total BETWEEN 0 AND 100', name='ck_cc_fit_scores'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trainer_id'], ['cc_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['weights_id', 'competency_weight', 'experience_weight', 'effectiveness_weight', 'availability_weight', 'capacity_weight'], ['cc_trainer_fit_weights.id', 'cc_trainer_fit_weights.competency_weight', 'cc_trainer_fit_weights.experience_weight', 'cc_trainer_fit_weights.effectiveness_weight', 'cc_trainer_fit_weights.availability_weight', 'cc_trainer_fit_weights.capacity_weight'], name='fk_cc_fit_evaluation_policy', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cc_fit_course_rank', 'cc_trainer_fit_evaluation', ['course_id', 'eligibility_status', 'weighted_total'], unique=False)
    op.create_index('ix_cc_fit_trainer_time', 'cc_trainer_fit_evaluation', ['trainer_id', 'evaluated_at'], unique=False)
    op.create_index(op.f('ix_cc_trainer_fit_evaluation_course_id'), 'cc_trainer_fit_evaluation', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_trainer_fit_evaluation_trainer_id'), 'cc_trainer_fit_evaluation', ['trainer_id'], unique=False)
    op.create_index(op.f('ix_cc_trainer_fit_evaluation_weights_id'), 'cc_trainer_fit_evaluation', ['weights_id'], unique=False)
    op.create_table('cc_trainer_team_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('weights_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('eligibility_status', sa.String(length=24), nullable=False),
    sa.Column('coverage_percent', sa.Float(), nullable=False),
    sa.Column('weighted_total', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("eligibility_status IN ('eligible', 'ineligible', 'insufficient_evidence')", name='ck_cc_team_match_eligibility'),
    sa.CheckConstraint("status IN ('proposed', 'accepted', 'rejected', 'superseded')", name='ck_cc_team_match_status'),
    sa.CheckConstraint('coverage_percent BETWEEN 0 AND 100 AND weighted_total BETWEEN 0 AND 100', name='ck_cc_team_match_scores'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['weights_id'], ['cc_trainer_fit_weights.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cc_team_course_status', 'cc_trainer_team_match', ['course_id', 'status'], unique=False)
    op.create_index(op.f('ix_cc_trainer_team_match_course_id'), 'cc_trainer_team_match', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_trainer_team_match_weights_id'), 'cc_trainer_team_match', ['weights_id'], unique=False)
    op.create_table('cc_training_effectiveness_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('participants', sa.Integer(), nullable=False),
    sa.Column('completions', sa.Integer(), nullable=False),
    sa.Column('assessment_pairs', sa.Integer(), nullable=False),
    sa.Column('observation_pairs', sa.Integer(), nullable=False),
    sa.Column('feedback_count', sa.Integer(), nullable=False),
    sa.Column('pre_average', sa.Float(), nullable=True),
    sa.Column('post_average', sa.Float(), nullable=True),
    sa.Column('assessment_improvement', sa.Float(), nullable=True),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('feedback_average', sa.Float(), nullable=True),
    sa.Column('feedback_summary', sa.Text(), nullable=False),
    sa.Column('pre_competency_average', sa.Float(), nullable=True),
    sa.Column('post_competency_average', sa.Float(), nullable=True),
    sa.Column('observed_competency_improvement', sa.Float(), nullable=True),
    sa.Column('interpretation', sa.String(length=32), server_default='observational_not_causal', nullable=False),
    sa.Column('methodology', sa.Text(), nullable=False),
    sa.Column('cohort_reference', sa.String(length=160), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("interpretation = 'observational_not_causal'", name='ck_cc_effectiveness_interpretation'),
    sa.CheckConstraint('assessment_improvement BETWEEN -100 AND 100', name='ck_cc_effectiveness_assessment_delta'),
    sa.CheckConstraint('feedback_average BETWEEN 1 AND 5 AND pre_competency_average BETWEEN 1 AND 5 AND post_competency_average BETWEEN 1 AND 5', name='ck_cc_effectiveness_averages'),
    sa.CheckConstraint('observed_competency_improvement BETWEEN -4 AND 4', name='ck_cc_effectiveness_competency_delta'),
    sa.CheckConstraint('participants >= 0 AND completions BETWEEN 0 AND participants AND assessment_pairs BETWEEN 0 AND participants AND observation_pairs BETWEEN 0 AND participants AND feedback_count BETWEEN 0 AND participants', name='ck_cc_effectiveness_counts'),
    sa.CheckConstraint('period_end > period_start', name='ck_cc_effectiveness_period'),
    sa.CheckConstraint('pre_average BETWEEN 0 AND 100 AND post_average BETWEEN 0 AND 100 AND pass_rate BETWEEN 0 AND 100', name='ck_cc_effectiveness_percentages'),
    sa.ForeignKeyConstraint(['competency_id'], ['cc_competency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cc_effectiveness_course_time', 'cc_training_effectiveness_snapshot', ['course_id', 'calculated_at'], unique=False)
    op.create_index(op.f('ix_cc_training_effectiveness_snapshot_competency_id'), 'cc_training_effectiveness_snapshot', ['competency_id'], unique=False)
    op.create_index(op.f('ix_cc_training_effectiveness_snapshot_course_id'), 'cc_training_effectiveness_snapshot', ['course_id'], unique=False)
    op.create_table('cc_training_program_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 1', name='ck_cc_program_course_position'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['program_id'], ['cc_training_program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'course_id', name='uq_cc_program_course'),
    sa.UniqueConstraint('program_id', 'position', name='uq_cc_program_course_order')
    )
    op.create_index(op.f('ix_cc_training_program_course_course_id'), 'cc_training_program_course', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_training_program_course_program_id'), 'cc_training_program_course', ['program_id'], unique=False)
    op.create_table('cc_user_organization_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'ended', 'pending')", name='ck_cc_user_org_status'),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name='ck_cc_user_org_dates'),
    sa.ForeignKeyConstraint(['department_id', 'organization_id'], ['cc_department.id', 'cc_department.organization_id'], name='fk_cc_user_org_department', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['cc_organization.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id', 'organization_id'], ['cc_organizational_role.id', 'cc_organizational_role.organization_id'], name='fk_cc_user_org_role', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'department_id', 'role_id', 'starts_at', name='uq_cc_user_org_assignment')
    )
    op.create_index('ix_cc_user_org_active', 'cc_user_organization_assignment', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_cc_user_organization_assignment_department_id'), 'cc_user_organization_assignment', ['department_id'], unique=False)
    op.create_index(op.f('ix_cc_user_organization_assignment_organization_id'), 'cc_user_organization_assignment', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cc_user_organization_assignment_role_id'), 'cc_user_organization_assignment', ['role_id'], unique=False)
    op.create_index(op.f('ix_cc_user_organization_assignment_user_id'), 'cc_user_organization_assignment', ['user_id'], unique=False)
    op.create_table('cc_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_cc_lesson_status'),
    sa.CheckConstraint('position >= 1 AND duration_minutes >= 0', name='ck_cc_lesson_numbers'),
    sa.ForeignKeyConstraint(['module_id'], ['cc_course_module.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'position', name='uq_cc_lesson_order')
    )
    op.create_index(op.f('ix_cc_lesson_module_id'), 'cc_lesson', ['module_id'], unique=False)
    op.create_table('cc_notification_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_state', sa.String(length=16), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(read_state = 'unread' AND read_at IS NULL) OR (read_state IN ('read', 'dismissed') AND read_at IS NOT NULL)", name='ck_cc_notification_read_time'),
    sa.CheckConstraint("read_state IN ('unread', 'read', 'dismissed')", name='ck_cc_notification_read_state'),
    sa.ForeignKeyConstraint(['notification_id'], ['cc_notification.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'user_id', name='uq_cc_notification_receipt')
    )
    op.create_index(op.f('ix_cc_notification_receipt_notification_id'), 'cc_notification_receipt', ['notification_id'], unique=False)
    op.create_index(op.f('ix_cc_notification_receipt_user_id'), 'cc_notification_receipt', ['user_id'], unique=False)
    op.create_index('ix_cc_notification_user_read', 'cc_notification_receipt', ['user_id', 'read_state'], unique=False)
    op.create_table('cc_role_competency_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('capacity_need_id', sa.Integer(), nullable=True),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('population_count', sa.Integer(), nullable=False),
    sa.Column('demand_count', sa.Integer(), nullable=False),
    sa.Column('population_context', sa.Text(), nullable=False),
    sa.Column('demand_context', sa.Text(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('population_count >= 0 AND demand_count >= 0 AND demand_count <= population_count', name='ck_cc_role_comp_population'),
    sa.CheckConstraint('required_level BETWEEN 1 AND 5', name='ck_cc_role_comp_level'),
    sa.ForeignKeyConstraint(['capacity_need_id'], ['cc_organizational_capacity_need.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['competency_id'], ['cc_competency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['cc_organizational_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'competency_id', name='uq_cc_role_competency')
    )
    op.create_index(op.f('ix_cc_role_competency_requirement_capacity_need_id'), 'cc_role_competency_requirement', ['capacity_need_id'], unique=False)
    op.create_index(op.f('ix_cc_role_competency_requirement_competency_id'), 'cc_role_competency_requirement', ['competency_id'], unique=False)
    op.create_index(op.f('ix_cc_role_competency_requirement_role_id'), 'cc_role_competency_requirement', ['role_id'], unique=False)
    op.create_table('cc_trainer_team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_match_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('fit_evaluation_id', sa.Integer(), nullable=True),
    sa.Column('member_role', sa.String(length=16), nullable=False),
    sa.Column('allocated_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("member_role IN ('lead', 'co_trainer', 'guest')", name='ck_cc_team_member_role'),
    sa.CheckConstraint('allocated_hours >= 0', name='ck_cc_team_member_hours'),
    sa.ForeignKeyConstraint(['fit_evaluation_id'], ['cc_trainer_fit_evaluation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_match_id'], ['cc_trainer_team_match.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['cc_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'team_match_id', name='uq_cc_team_member_team'),
    sa.UniqueConstraint('team_match_id', 'trainer_id', name='uq_cc_team_member')
    )
    op.create_index(op.f('ix_cc_trainer_team_member_fit_evaluation_id'), 'cc_trainer_team_member', ['fit_evaluation_id'], unique=False)
    op.create_index(op.f('ix_cc_trainer_team_member_team_match_id'), 'cc_trainer_team_member', ['team_match_id'], unique=False)
    op.create_index(op.f('ix_cc_trainer_team_member_trainer_id'), 'cc_trainer_team_member', ['trainer_id'], unique=False)
    op.create_table('cc_competency_gap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('capacity_need_id', sa.Integer(), nullable=True),
    sa.Column('role_requirement_id', sa.Integer(), nullable=True),
    sa.Column('baseline_level', sa.Integer(), nullable=True),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('identified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('identified', 'in_progress', 'closed', 'superseded')", name='ck_cc_gap_status'),
    sa.CheckConstraint('baseline_level BETWEEN 1 AND 5 AND required_level BETWEEN 1 AND 5', name='ck_cc_gap_levels'),
    sa.ForeignKeyConstraint(['capacity_need_id'], ['cc_organizational_capacity_need.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['competency_id'], ['cc_competency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_requirement_id'], ['cc_role_competency_requirement.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', name='uq_cc_gap_user')
    )
    op.create_index(op.f('ix_cc_competency_gap_capacity_need_id'), 'cc_competency_gap', ['capacity_need_id'], unique=False)
    op.create_index(op.f('ix_cc_competency_gap_competency_id'), 'cc_competency_gap', ['competency_id'], unique=False)
    op.create_index(op.f('ix_cc_competency_gap_role_requirement_id'), 'cc_competency_gap', ['role_requirement_id'], unique=False)
    op.create_index(op.f('ix_cc_competency_gap_user_id'), 'cc_competency_gap', ['user_id'], unique=False)
    op.create_index('ix_cc_gap_user_status', 'cc_competency_gap', ['user_id', 'status'], unique=False)
    op.create_table('cc_lesson_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 1', name='ck_cc_lesson_resource_position'),
    sa.ForeignKeyConstraint(['lesson_id'], ['cc_lesson.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['cc_learning_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'position', name='uq_cc_lesson_resource_order'),
    sa.UniqueConstraint('lesson_id', 'resource_id', name='uq_cc_lesson_resource')
    )
    op.create_index(op.f('ix_cc_lesson_resource_lesson_id'), 'cc_lesson_resource', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_cc_lesson_resource_resource_id'), 'cc_lesson_resource', ['resource_id'], unique=False)
    op.create_table('cc_practice_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('marks_awarded', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('in_progress', 'submitted', 'graded', 'abandoned')", name='ck_cc_practice_attempt_status'),
    sa.CheckConstraint('max_marks >= 0 AND marks_awarded >= 0 AND marks_awarded <= max_marks', name='ck_cc_practice_attempt_marks'),
    sa.CheckConstraint('percentage BETWEEN 0 AND 100', name='ck_cc_practice_attempt_percentage'),
    sa.CheckConstraint('submitted_at IS NULL OR submitted_at >= started_at', name='ck_cc_practice_attempt_time'),
    sa.ForeignKeyConstraint(['lesson_id'], ['cc_lesson.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cc_practice_attempt_lesson_id'), 'cc_practice_attempt', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_cc_practice_attempt_user_id'), 'cc_practice_attempt', ['user_id'], unique=False)
    op.create_index('ix_cc_practice_user_status', 'cc_practice_attempt', ['user_id', 'status'], unique=False)
    op.create_table('cc_practice_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('answer_rubric', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=24), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("question_type IN ('single_choice', 'multiple_choice', 'short_answer')", name='ck_cc_practice_question_type'),
    sa.CheckConstraint("status IN ('draft', 'published', 'archived')", name='ck_cc_practice_question_status'),
    sa.CheckConstraint('difficulty_level BETWEEN 1 AND 5', name='ck_cc_practice_question_level'),
    sa.CheckConstraint('max_marks > 0', name='ck_cc_practice_question_marks'),
    sa.ForeignKeyConstraint(['competency_id'], ['cc_competency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['cc_lesson.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cc_practice_question_competency_id'), 'cc_practice_question', ['competency_id'], unique=False)
    op.create_index(op.f('ix_cc_practice_question_course_id'), 'cc_practice_question', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_practice_question_lesson_id'), 'cc_practice_question', ['lesson_id'], unique=False)
    op.create_table('cc_trainer_team_competency_coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_match_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('covered_level', sa.Integer(), nullable=True),
    sa.Column('coverage_status', sa.String(length=16), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(coverage_status = 'uncovered' AND member_id IS NULL AND covered_level IS NULL) OR (coverage_status = 'partial' AND member_id IS NOT NULL AND covered_level IS NOT NULL AND covered_level < required_level) OR (coverage_status = 'covered' AND member_id IS NOT NULL AND covered_level IS NOT NULL AND covered_level >= required_level)", name='ck_cc_team_coverage_status'),
    sa.CheckConstraint('required_level BETWEEN 1 AND 5 AND covered_level BETWEEN 1 AND 5', name='ck_cc_team_coverage_levels'),
    sa.ForeignKeyConstraint(['competency_id'], ['cc_competency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['member_id', 'team_match_id'], ['cc_trainer_team_member.id', 'cc_trainer_team_member.team_match_id'], name='fk_cc_team_coverage_member', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_match_id'], ['cc_trainer_team_match.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_match_id', 'competency_id', name='uq_cc_team_competency_coverage')
    )
    op.create_index(op.f('ix_cc_trainer_team_competency_coverage_competency_id'), 'cc_trainer_team_competency_coverage', ['competency_id'], unique=False)
    op.create_index(op.f('ix_cc_trainer_team_competency_coverage_member_id'), 'cc_trainer_team_competency_coverage', ['member_id'], unique=False)
    op.create_index(op.f('ix_cc_trainer_team_competency_coverage_team_match_id'), 'cc_trainer_team_competency_coverage', ['team_match_id'], unique=False)
    op.create_table('cc_capacity_ai_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('user_action', sa.String(length=32), nullable=False),
    sa.Column('request_text', sa.String(length=8000), nullable=False),
    sa.Column('response_text', sa.String(length=24000), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('gap_id', sa.Integer(), nullable=True),
    sa.Column('learning_path_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('practice_question_id', sa.Integer(), nullable=True),
    sa.Column('fit_evaluation_id', sa.Integer(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'completed', 'blocked', 'failed')", name='ck_cc_ai_message_status'),
    sa.CheckConstraint("user_action IN ('explain', 'summarize', 'recommend_learning', 'practice_help', 'explain_gap', 'explain_trainer_fit', 'general_help')", name='ck_cc_ai_message_action'),
    sa.CheckConstraint('length(request_text) <= 8000 AND length(response_text) <= 24000', name='ck_cc_ai_message_bounds'),
    sa.CheckConstraint('position >= 1', name='ck_cc_ai_message_position'),
    sa.ForeignKeyConstraint(['competency_id'], ['cc_competency.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['cc_capacity_ai_conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fit_evaluation_id'], ['cc_trainer_fit_evaluation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gap_id'], ['cc_competency_gap.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learning_path_id'], ['cc_learning_path.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_id'], ['cc_lesson.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practice_question_id'], ['cc_practice_question.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['cc_learning_resource.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'position', name='uq_cc_ai_message_order')
    )
    op.create_index('ix_cc_ai_message_conversation_time', 'cc_capacity_ai_message', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_cc_capacity_ai_message_competency_id'), 'cc_capacity_ai_message', ['competency_id'], unique=False)
    op.create_index(op.f('ix_cc_capacity_ai_message_conversation_id'), 'cc_capacity_ai_message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_cc_capacity_ai_message_course_id'), 'cc_capacity_ai_message', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_capacity_ai_message_fit_evaluation_id'), 'cc_capacity_ai_message', ['fit_evaluation_id'], unique=False)
    op.create_index(op.f('ix_cc_capacity_ai_message_gap_id'), 'cc_capacity_ai_message', ['gap_id'], unique=False)
    op.create_index(op.f('ix_cc_capacity_ai_message_learning_path_id'), 'cc_capacity_ai_message', ['learning_path_id'], unique=False)
    op.create_index(op.f('ix_cc_capacity_ai_message_lesson_id'), 'cc_capacity_ai_message', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_cc_capacity_ai_message_practice_question_id'), 'cc_capacity_ai_message', ['practice_question_id'], unique=False)
    op.create_index(op.f('ix_cc_capacity_ai_message_resource_id'), 'cc_capacity_ai_message', ['resource_id'], unique=False)
    op.create_table('cc_competency_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=24), nullable=False),
    sa.Column('source_system', sa.String(length=80), nullable=False),
    sa.Column('source_reference', sa.String(length=200), nullable=False),
    sa.Column('assessment_result_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('practice_attempt_id', sa.Integer(), nullable=True),
    sa.Column('measured_level', sa.Integer(), nullable=True),
    sa.Column('measured_score', sa.Float(), nullable=True, comment='Percentage 0–100; not an AI score.'),
    sa.Column('verifier_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(evidence_type IN ('official_assessment', 'final_assessment') AND assessment_result_id IS NOT NULL AND practice_attempt_id IS NULL) OR (evidence_type = 'practice' AND practice_attempt_id IS NOT NULL AND assessment_result_id IS NULL) OR (evidence_type = 'course_completion' AND enrollment_id IS NOT NULL AND assessment_result_id IS NULL AND practice_attempt_id IS NULL) OR (evidence_type IN ('questionnaire', 'trainer_evaluation') AND assessment_result_id IS NULL AND practice_attempt_id IS NULL)", name='ck_cc_evidence_source_kind'),
    sa.CheckConstraint("evidence_type IN ('official_assessment', 'questionnaire', 'trainer_evaluation', 'course_completion', 'practice', 'final_assessment')", name='ck_cc_evidence_type'),
    sa.CheckConstraint("verification_status <> 'verified' OR (verifier_id IS NOT NULL AND verified_at IS NOT NULL)", name='ck_cc_evidence_verified'),
    sa.CheckConstraint("verification_status IN ('pending', 'verified', 'rejected', 'revoked')", name='ck_cc_evidence_status'),
    sa.CheckConstraint('length(source_reference) > 0 AND length(source_system) > 0', name='ck_cc_evidence_reference'),
    sa.CheckConstraint('measured_level BETWEEN 1 AND 5', name='ck_cc_evidence_level'),
    sa.CheckConstraint('measured_level IS NOT NULL OR measured_score IS NOT NULL', name='ck_cc_evidence_measurement'),
    sa.CheckConstraint('measured_score BETWEEN 0 AND 100', name='ck_cc_evidence_score'),
    sa.CheckConstraint('verified_at IS NULL OR verified_at >= observed_at', name='ck_cc_evidence_time'),
    sa.ForeignKeyConstraint(['assessment_result_id'], ['cc_assessment_result.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['competency_id'], ['cc_competency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['cc_enrollment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['practice_attempt_id'], ['cc_practice_attempt.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verifier_id'], ['cc_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'user_id', 'competency_id', 'measured_level', 'verification_status', 'verified_at', name='uq_cc_evidence_snapshot_basis'),
    sa.UniqueConstraint('user_id', 'competency_id', 'evidence_type', 'source_system', 'source_reference', name='uq_cc_evidence_source')
    )
    op.create_index(op.f('ix_cc_competency_evidence_assessment_result_id'), 'cc_competency_evidence', ['assessment_result_id'], unique=False)
    op.create_index(op.f('ix_cc_competency_evidence_competency_id'), 'cc_competency_evidence', ['competency_id'], unique=False)
    op.create_index(op.f('ix_cc_competency_evidence_enrollment_id'), 'cc_competency_evidence', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_cc_competency_evidence_practice_attempt_id'), 'cc_competency_evidence', ['practice_attempt_id'], unique=False)
    op.create_index(op.f('ix_cc_competency_evidence_user_id'), 'cc_competency_evidence', ['user_id'], unique=False)
    op.create_index(op.f('ix_cc_competency_evidence_verifier_id'), 'cc_competency_evidence', ['verifier_id'], unique=False)
    op.create_index('ix_cc_evidence_user_status', 'cc_competency_evidence', ['user_id', 'competency_id', 'verification_status'], unique=False)
    op.create_table('cc_learning_path_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gap_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=16), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('practice_question_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(step_type = 'course' AND course_id IS NOT NULL) OR (step_type = 'module' AND module_id IS NOT NULL) OR (step_type = 'lesson' AND lesson_id IS NOT NULL) OR (step_type = 'resource' AND resource_id IS NOT NULL) OR (step_type = 'practice' AND practice_question_id IS NOT NULL) OR (step_type = 'assessment' AND assessment_id IS NOT NULL)", name='ck_cc_path_step_type'),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'completed', 'skipped')", name='ck_cc_path_step_status'),
    sa.CheckConstraint('(CASE WHEN course_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN module_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN lesson_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN resource_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN practice_question_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN assessment_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_cc_path_step_one_target'),
    sa.CheckConstraint('position >= 1', name='ck_cc_path_step_position'),
    sa.ForeignKeyConstraint(['assessment_id'], ['cc_assessment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gap_id', 'user_id'], ['cc_competency_gap.id', 'cc_competency_gap.user_id'], name='fk_cc_path_step_gap', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lesson_id'], ['cc_lesson.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['module_id'], ['cc_course_module.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['path_id', 'user_id'], ['cc_learning_path.id', 'cc_learning_path.user_id'], name='fk_cc_path_step_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_question_id'], ['cc_practice_question.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resource_id'], ['cc_learning_resource.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id', 'position', name='uq_cc_path_step_order')
    )
    op.create_index(op.f('ix_cc_learning_path_step_assessment_id'), 'cc_learning_path_step', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_cc_learning_path_step_course_id'), 'cc_learning_path_step', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_learning_path_step_gap_id'), 'cc_learning_path_step', ['gap_id'], unique=False)
    op.create_index(op.f('ix_cc_learning_path_step_lesson_id'), 'cc_learning_path_step', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_cc_learning_path_step_module_id'), 'cc_learning_path_step', ['module_id'], unique=False)
    op.create_index(op.f('ix_cc_learning_path_step_path_id'), 'cc_learning_path_step', ['path_id'], unique=False)
    op.create_index(op.f('ix_cc_learning_path_step_practice_question_id'), 'cc_learning_path_step', ['practice_question_id'], unique=False)
    op.create_index(op.f('ix_cc_learning_path_step_resource_id'), 'cc_learning_path_step', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cc_learning_path_step_user_id'), 'cc_learning_path_step', ['user_id'], unique=False)
    op.create_table('cc_practice_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('prompt_snapshot', sa.Text(), nullable=False),
    sa.Column('rubric_snapshot', sa.Text(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('marks_awarded', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('grader_id', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_marks > 0 AND marks_awarded >= 0 AND marks_awarded <= max_marks', name='ck_cc_practice_answer_marks'),
    sa.ForeignKeyConstraint(['attempt_id'], ['cc_practice_attempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grader_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['cc_practice_question.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_cc_practice_answer'),
    sa.UniqueConstraint('id', 'question_id', name='uq_cc_practice_answer_question')
    )
    op.create_index(op.f('ix_cc_practice_answer_attempt_id'), 'cc_practice_answer', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_cc_practice_answer_grader_id'), 'cc_practice_answer', ['grader_id'], unique=False)
    op.create_index(op.f('ix_cc_practice_answer_question_id'), 'cc_practice_answer', ['question_id'], unique=False)
    op.create_table('cc_practice_question_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.CheckConstraint('position >= 1', name='ck_cc_practice_option_position'),
    sa.ForeignKeyConstraint(['question_id'], ['cc_practice_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'question_id', name='uq_cc_practice_option_question'),
    sa.UniqueConstraint('question_id', 'position', name='uq_cc_practice_option_position')
    )
    op.create_index(op.f('ix_cc_practice_question_option_question_id'), 'cc_practice_question_option', ['question_id'], unique=False)
    op.create_table('cc_capacity_ai_message_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_identifier', sa.String(length=200), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('page_locator', sa.String(length=100), nullable=False),
    sa.Column('excerpt', sa.String(length=2000), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('course', 'lesson', 'resource', 'competency', 'evidence', 'public_reference')", name='ck_cc_ai_source_type'),
    sa.CheckConstraint('length(excerpt) <= 2000', name='ck_cc_ai_source_excerpt'),
    sa.CheckConstraint('position BETWEEN 1 AND 20', name='ck_cc_ai_source_bound'),
    sa.ForeignKeyConstraint(['message_id'], ['cc_capacity_ai_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'position', name='uq_cc_ai_source_position')
    )
    op.create_index(op.f('ix_cc_capacity_ai_message_source_message_id'), 'cc_capacity_ai_message_source', ['message_id'], unique=False)
    op.create_table('cc_certificate_competency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('certified_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('certified_level BETWEEN 1 AND 5', name='ck_cc_certificate_comp_level'),
    sa.ForeignKeyConstraint(['certificate_id'], ['cc_certificate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competency_id'], ['cc_competency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id'], ['cc_competency_evidence.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_id', 'competency_id', name='uq_cc_certificate_competency')
    )
    op.create_index(op.f('ix_cc_certificate_competency_certificate_id'), 'cc_certificate_competency', ['certificate_id'], unique=False)
    op.create_index(op.f('ix_cc_certificate_competency_competency_id'), 'cc_certificate_competency', ['competency_id'], unique=False)
    op.create_index(op.f('ix_cc_certificate_competency_evidence_id'), 'cc_certificate_competency', ['evidence_id'], unique=False)
    op.create_table('cc_competency_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('observer_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('observed_level', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("phase IN ('pre', 'post', 'follow_up')", name='ck_cc_observation_phase'),
    sa.CheckConstraint("verification_status <> 'verified' OR (observer_id IS NOT NULL AND verified_at IS NOT NULL)", name='ck_cc_observation_verified'),
    sa.CheckConstraint("verification_status IN ('pending', 'verified', 'rejected')", name='ck_cc_observation_status'),
    sa.CheckConstraint('observed_level BETWEEN 1 AND 5', name='ck_cc_observation_level'),
    sa.ForeignKeyConstraint(['competency_id'], ['cc_competency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id'], ['cc_competency_evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['observer_id'], ['cc_user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'user_id', 'competency_id', 'phase', 'observed_at', name='uq_cc_competency_observation')
    )
    op.create_index(op.f('ix_cc_competency_observation_competency_id'), 'cc_competency_observation', ['competency_id'], unique=False)
    op.create_index(op.f('ix_cc_competency_observation_course_id'), 'cc_competency_observation', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_competency_observation_evidence_id'), 'cc_competency_observation', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_cc_competency_observation_observer_id'), 'cc_competency_observation', ['observer_id'], unique=False)
    op.create_index(op.f('ix_cc_competency_observation_user_id'), 'cc_competency_observation', ['user_id'], unique=False)
    op.create_index('ix_cc_observation_course_phase', 'cc_competency_observation', ['course_id', 'phase', 'competency_id'], unique=False)
    op.create_table('cc_practice_answer_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id', 'question_id'], ['cc_practice_answer.id', 'cc_practice_answer.question_id'], name='fk_cc_practice_selection_answer', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id', 'question_id'], ['cc_practice_question_option.id', 'cc_practice_question_option.question_id'], name='fk_cc_practice_selection_option', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id', 'option_id', name='uq_cc_practice_selection')
    )
    op.create_index(op.f('ix_cc_practice_answer_selection_answer_id'), 'cc_practice_answer_selection', ['answer_id'], unique=False)
    op.create_index(op.f('ix_cc_practice_answer_selection_option_id'), 'cc_practice_answer_selection', ['option_id'], unique=False)
    op.create_index(op.f('ix_cc_practice_answer_selection_question_id'), 'cc_practice_answer_selection', ['question_id'], unique=False)
    op.create_table('cc_user_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('awarded', 'revoked')", name='ck_cc_user_achievement_status'),
    sa.ForeignKeyConstraint(['achievement_id'], ['cc_achievement.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_id'], ['cc_competency_evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_cc_user_achievement')
    )
    op.create_index(op.f('ix_cc_user_achievement_achievement_id'), 'cc_user_achievement', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_cc_user_achievement_course_id'), 'cc_user_achievement', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_user_achievement_evidence_id'), 'cc_user_achievement', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_cc_user_achievement_user_id'), 'cc_user_achievement', ['user_id'], unique=False)
    op.create_table('cc_user_competency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('target_level', sa.Integer(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(verification_status = 'unmeasured' AND current_level IS NULL AND evidence_id IS NULL AND last_verified_at IS NULL) OR (verification_status = 'verified' AND current_level IS NOT NULL AND evidence_id IS NOT NULL AND last_verified_at IS NOT NULL)", name='ck_cc_snapshot_verified_only'),
    sa.CheckConstraint('current_level BETWEEN 1 AND 5', name='ck_cc_user_comp_current'),
    sa.CheckConstraint('target_level BETWEEN 1 AND 5', name='ck_cc_user_comp_target'),
    sa.ForeignKeyConstraint(['competency_id'], ['cc_competency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['evidence_id', 'user_id', 'competency_id', 'current_level', 'verification_status', 'last_verified_at'], ['cc_competency_evidence.id', 'cc_competency_evidence.user_id', 'cc_competency_evidence.competency_id', 'cc_competency_evidence.measured_level', 'cc_competency_evidence.verification_status', 'cc_competency_evidence.verified_at'], name='fk_cc_snapshot_verified_evidence', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'competency_id', name='uq_cc_user_competency')
    )
    op.create_index('ix_cc_user_comp_level', 'cc_user_competency', ['competency_id', 'current_level'], unique=False)
    op.create_index(op.f('ix_cc_user_competency_competency_id'), 'cc_user_competency', ['competency_id'], unique=False)
    op.create_index(op.f('ix_cc_user_competency_evidence_id'), 'cc_user_competency', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_cc_user_competency_user_id'), 'cc_user_competency', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cc_user_competency_user_id'), table_name='cc_user_competency')
    op.drop_index(op.f('ix_cc_user_competency_evidence_id'), table_name='cc_user_competency')
    op.drop_index(op.f('ix_cc_user_competency_competency_id'), table_name='cc_user_competency')
    op.drop_index('ix_cc_user_comp_level', table_name='cc_user_competency')
    op.drop_table('cc_user_competency')
    op.drop_index(op.f('ix_cc_user_achievement_user_id'), table_name='cc_user_achievement')
    op.drop_index(op.f('ix_cc_user_achievement_evidence_id'), table_name='cc_user_achievement')
    op.drop_index(op.f('ix_cc_user_achievement_course_id'), table_name='cc_user_achievement')
    op.drop_index(op.f('ix_cc_user_achievement_achievement_id'), table_name='cc_user_achievement')
    op.drop_table('cc_user_achievement')
    op.drop_index(op.f('ix_cc_practice_answer_selection_question_id'), table_name='cc_practice_answer_selection')
    op.drop_index(op.f('ix_cc_practice_answer_selection_option_id'), table_name='cc_practice_answer_selection')
    op.drop_index(op.f('ix_cc_practice_answer_selection_answer_id'), table_name='cc_practice_answer_selection')
    op.drop_table('cc_practice_answer_selection')
    op.drop_index('ix_cc_observation_course_phase', table_name='cc_competency_observation')
    op.drop_index(op.f('ix_cc_competency_observation_user_id'), table_name='cc_competency_observation')
    op.drop_index(op.f('ix_cc_competency_observation_observer_id'), table_name='cc_competency_observation')
    op.drop_index(op.f('ix_cc_competency_observation_evidence_id'), table_name='cc_competency_observation')
    op.drop_index(op.f('ix_cc_competency_observation_course_id'), table_name='cc_competency_observation')
    op.drop_index(op.f('ix_cc_competency_observation_competency_id'), table_name='cc_competency_observation')
    op.drop_table('cc_competency_observation')
    op.drop_index(op.f('ix_cc_certificate_competency_evidence_id'), table_name='cc_certificate_competency')
    op.drop_index(op.f('ix_cc_certificate_competency_competency_id'), table_name='cc_certificate_competency')
    op.drop_index(op.f('ix_cc_certificate_competency_certificate_id'), table_name='cc_certificate_competency')
    op.drop_table('cc_certificate_competency')
    op.drop_index(op.f('ix_cc_capacity_ai_message_source_message_id'), table_name='cc_capacity_ai_message_source')
    op.drop_table('cc_capacity_ai_message_source')
    op.drop_index(op.f('ix_cc_practice_question_option_question_id'), table_name='cc_practice_question_option')
    op.drop_table('cc_practice_question_option')
    op.drop_index(op.f('ix_cc_practice_answer_question_id'), table_name='cc_practice_answer')
    op.drop_index(op.f('ix_cc_practice_answer_grader_id'), table_name='cc_practice_answer')
    op.drop_index(op.f('ix_cc_practice_answer_attempt_id'), table_name='cc_practice_answer')
    op.drop_table('cc_practice_answer')
    op.drop_index(op.f('ix_cc_learning_path_step_user_id'), table_name='cc_learning_path_step')
    op.drop_index(op.f('ix_cc_learning_path_step_resource_id'), table_name='cc_learning_path_step')
    op.drop_index(op.f('ix_cc_learning_path_step_practice_question_id'), table_name='cc_learning_path_step')
    op.drop_index(op.f('ix_cc_learning_path_step_path_id'), table_name='cc_learning_path_step')
    op.drop_index(op.f('ix_cc_learning_path_step_module_id'), table_name='cc_learning_path_step')
    op.drop_index(op.f('ix_cc_learning_path_step_lesson_id'), table_name='cc_learning_path_step')
    op.drop_index(op.f('ix_cc_learning_path_step_gap_id'), table_name='cc_learning_path_step')
    op.drop_index(op.f('ix_cc_learning_path_step_course_id'), table_name='cc_learning_path_step')
    op.drop_index(op.f('ix_cc_learning_path_step_assessment_id'), table_name='cc_learning_path_step')
    op.drop_table('cc_learning_path_step')
    op.drop_index('ix_cc_evidence_user_status', table_name='cc_competency_evidence')
    op.drop_index(op.f('ix_cc_competency_evidence_verifier_id'), table_name='cc_competency_evidence')
    op.drop_index(op.f('ix_cc_competency_evidence_user_id'), table_name='cc_competency_evidence')
    op.drop_index(op.f('ix_cc_competency_evidence_practice_attempt_id'), table_name='cc_competency_evidence')
    op.drop_index(op.f('ix_cc_competency_evidence_enrollment_id'), table_name='cc_competency_evidence')
    op.drop_index(op.f('ix_cc_competency_evidence_competency_id'), table_name='cc_competency_evidence')
    op.drop_index(op.f('ix_cc_competency_evidence_assessment_result_id'), table_name='cc_competency_evidence')
    op.drop_table('cc_competency_evidence')
    op.drop_index(op.f('ix_cc_capacity_ai_message_resource_id'), table_name='cc_capacity_ai_message')
    op.drop_index(op.f('ix_cc_capacity_ai_message_practice_question_id'), table_name='cc_capacity_ai_message')
    op.drop_index(op.f('ix_cc_capacity_ai_message_lesson_id'), table_name='cc_capacity_ai_message')
    op.drop_index(op.f('ix_cc_capacity_ai_message_learning_path_id'), table_name='cc_capacity_ai_message')
    op.drop_index(op.f('ix_cc_capacity_ai_message_gap_id'), table_name='cc_capacity_ai_message')
    op.drop_index(op.f('ix_cc_capacity_ai_message_fit_evaluation_id'), table_name='cc_capacity_ai_message')
    op.drop_index(op.f('ix_cc_capacity_ai_message_course_id'), table_name='cc_capacity_ai_message')
    op.drop_index(op.f('ix_cc_capacity_ai_message_conversation_id'), table_name='cc_capacity_ai_message')
    op.drop_index(op.f('ix_cc_capacity_ai_message_competency_id'), table_name='cc_capacity_ai_message')
    op.drop_index('ix_cc_ai_message_conversation_time', table_name='cc_capacity_ai_message')
    op.drop_table('cc_capacity_ai_message')
    op.drop_index(op.f('ix_cc_trainer_team_competency_coverage_team_match_id'), table_name='cc_trainer_team_competency_coverage')
    op.drop_index(op.f('ix_cc_trainer_team_competency_coverage_member_id'), table_name='cc_trainer_team_competency_coverage')
    op.drop_index(op.f('ix_cc_trainer_team_competency_coverage_competency_id'), table_name='cc_trainer_team_competency_coverage')
    op.drop_table('cc_trainer_team_competency_coverage')
    op.drop_index(op.f('ix_cc_practice_question_lesson_id'), table_name='cc_practice_question')
    op.drop_index(op.f('ix_cc_practice_question_course_id'), table_name='cc_practice_question')
    op.drop_index(op.f('ix_cc_practice_question_competency_id'), table_name='cc_practice_question')
    op.drop_table('cc_practice_question')
    op.drop_index('ix_cc_practice_user_status', table_name='cc_practice_attempt')
    op.drop_index(op.f('ix_cc_practice_attempt_user_id'), table_name='cc_practice_attempt')
    op.drop_index(op.f('ix_cc_practice_attempt_lesson_id'), table_name='cc_practice_attempt')
    op.drop_table('cc_practice_attempt')
    op.drop_index(op.f('ix_cc_lesson_resource_resource_id'), table_name='cc_lesson_resource')
    op.drop_index(op.f('ix_cc_lesson_resource_lesson_id'), table_name='cc_lesson_resource')
    op.drop_table('cc_lesson_resource')
    op.drop_index('ix_cc_gap_user_status', table_name='cc_competency_gap')
    op.drop_index(op.f('ix_cc_competency_gap_user_id'), table_name='cc_competency_gap')
    op.drop_index(op.f('ix_cc_competency_gap_role_requirement_id'), table_name='cc_competency_gap')
    op.drop_index(op.f('ix_cc_competency_gap_competency_id'), table_name='cc_competency_gap')
    op.drop_index(op.f('ix_cc_competency_gap_capacity_need_id'), table_name='cc_competency_gap')
    op.drop_table('cc_competency_gap')
    op.drop_index(op.f('ix_cc_trainer_team_member_trainer_id'), table_name='cc_trainer_team_member')
    op.drop_index(op.f('ix_cc_trainer_team_member_team_match_id'), table_name='cc_trainer_team_member')
    op.drop_index(op.f('ix_cc_trainer_team_member_fit_evaluation_id'), table_name='cc_trainer_team_member')
    op.drop_table('cc_trainer_team_member')
    op.drop_index(op.f('ix_cc_role_competency_requirement_role_id'), table_name='cc_role_competency_requirement')
    op.drop_index(op.f('ix_cc_role_competency_requirement_competency_id'), table_name='cc_role_competency_requirement')
    op.drop_index(op.f('ix_cc_role_competency_requirement_capacity_need_id'), table_name='cc_role_competency_requirement')
    op.drop_table('cc_role_competency_requirement')
    op.drop_index('ix_cc_notification_user_read', table_name='cc_notification_receipt')
    op.drop_index(op.f('ix_cc_notification_receipt_user_id'), table_name='cc_notification_receipt')
    op.drop_index(op.f('ix_cc_notification_receipt_notification_id'), table_name='cc_notification_receipt')
    op.drop_table('cc_notification_receipt')
    op.drop_index(op.f('ix_cc_lesson_module_id'), table_name='cc_lesson')
    op.drop_table('cc_lesson')
    op.drop_index(op.f('ix_cc_user_organization_assignment_user_id'), table_name='cc_user_organization_assignment')
    op.drop_index(op.f('ix_cc_user_organization_assignment_role_id'), table_name='cc_user_organization_assignment')
    op.drop_index(op.f('ix_cc_user_organization_assignment_organization_id'), table_name='cc_user_organization_assignment')
    op.drop_index(op.f('ix_cc_user_organization_assignment_department_id'), table_name='cc_user_organization_assignment')
    op.drop_index('ix_cc_user_org_active', table_name='cc_user_organization_assignment')
    op.drop_table('cc_user_organization_assignment')
    op.drop_index(op.f('ix_cc_training_program_course_program_id'), table_name='cc_training_program_course')
    op.drop_index(op.f('ix_cc_training_program_course_course_id'), table_name='cc_training_program_course')
    op.drop_table('cc_training_program_course')
    op.drop_index(op.f('ix_cc_training_effectiveness_snapshot_course_id'), table_name='cc_training_effectiveness_snapshot')
    op.drop_index(op.f('ix_cc_training_effectiveness_snapshot_competency_id'), table_name='cc_training_effectiveness_snapshot')
    op.drop_index('ix_cc_effectiveness_course_time', table_name='cc_training_effectiveness_snapshot')
    op.drop_table('cc_training_effectiveness_snapshot')
    op.drop_index(op.f('ix_cc_trainer_team_match_weights_id'), table_name='cc_trainer_team_match')
    op.drop_index(op.f('ix_cc_trainer_team_match_course_id'), table_name='cc_trainer_team_match')
    op.drop_index('ix_cc_team_course_status', table_name='cc_trainer_team_match')
    op.drop_table('cc_trainer_team_match')
    op.drop_index(op.f('ix_cc_trainer_fit_evaluation_weights_id'), table_name='cc_trainer_fit_evaluation')
    op.drop_index(op.f('ix_cc_trainer_fit_evaluation_trainer_id'), table_name='cc_trainer_fit_evaluation')
    op.drop_index(op.f('ix_cc_trainer_fit_evaluation_course_id'), table_name='cc_trainer_fit_evaluation')
    op.drop_index('ix_cc_fit_trainer_time', table_name='cc_trainer_fit_evaluation')
    op.drop_index('ix_cc_fit_course_rank', table_name='cc_trainer_fit_evaluation')
    op.drop_table('cc_trainer_fit_evaluation')
    op.drop_index(op.f('ix_cc_organizational_capacity_need_organization_id'), table_name='cc_organizational_capacity_need')
    op.drop_index(op.f('ix_cc_organizational_capacity_need_department_id'), table_name='cc_organizational_capacity_need')
    op.drop_index(op.f('ix_cc_organizational_capacity_need_competency_id'), table_name='cc_organizational_capacity_need')
    op.drop_index('ix_cc_need_org_status', table_name='cc_organizational_capacity_need')
    op.drop_table('cc_organizational_capacity_need')
    op.drop_index(op.f('ix_cc_notification_user_id'), table_name='cc_notification')
    op.drop_index(op.f('ix_cc_notification_organization_id'), table_name='cc_notification')
    op.drop_index('ix_cc_notification_feed', table_name='cc_notification')
    op.drop_index(op.f('ix_cc_notification_course_id'), table_name='cc_notification')
    op.drop_table('cc_notification')
    op.drop_index('ix_cc_path_user_status', table_name='cc_learning_path')
    op.drop_index(op.f('ix_cc_learning_path_user_id'), table_name='cc_learning_path')
    op.drop_index(op.f('ix_cc_learning_path_program_id'), table_name='cc_learning_path')
    op.drop_table('cc_learning_path')
    op.drop_index(op.f('ix_cc_course_module_course_id'), table_name='cc_course_module')
    op.drop_table('cc_course_module')
    op.drop_index(op.f('ix_cc_course_competency_requirement_course_id'), table_name='cc_course_competency_requirement')
    op.drop_index(op.f('ix_cc_course_competency_requirement_competency_id'), table_name='cc_course_competency_requirement')
    op.drop_table('cc_course_competency_requirement')
    op.drop_index(op.f('ix_cc_training_program_status'), table_name='cc_training_program')
    op.drop_index(op.f('ix_cc_training_program_organization_id'), table_name='cc_training_program')
    op.drop_table('cc_training_program')
    op.drop_index(op.f('ix_cc_trainer_fit_weights_organization_id'), table_name='cc_trainer_fit_weights')
    op.drop_table('cc_trainer_fit_weights')
    op.drop_index(op.f('ix_cc_trainer_capacity_trainer_id'), table_name='cc_trainer_capacity')
    op.drop_index('ix_cc_capacity_trainer_period', table_name='cc_trainer_capacity')
    op.drop_table('cc_trainer_capacity')
    op.drop_index(op.f('ix_cc_trainer_availability_trainer_id'), table_name='cc_trainer_availability')
    op.drop_index('ix_cc_availability_trainer_window', table_name='cc_trainer_availability')
    op.drop_table('cc_trainer_availability')
    op.drop_index(op.f('ix_cc_organizational_role_organization_id'), table_name='cc_organizational_role')
    op.drop_table('cc_organizational_role')
    op.drop_index(op.f('ix_cc_department_organization_id'), table_name='cc_department')
    op.drop_table('cc_department')
    op.drop_index(op.f('ix_cc_competency_subject_id'), table_name='cc_competency')
    op.drop_index(op.f('ix_cc_competency_is_active'), table_name='cc_competency')
    op.drop_table('cc_competency')
    op.drop_index(op.f('ix_cc_capacity_ai_conversation_user_id'), table_name='cc_capacity_ai_conversation')
    op.drop_index('ix_cc_ai_conversation_user_time', table_name='cc_capacity_ai_conversation')
    op.drop_table('cc_capacity_ai_conversation')
    op.drop_index(op.f('ix_cc_subject_name'), table_name='cc_subject')
    op.drop_table('cc_subject')
    op.drop_index(op.f('ix_cc_organization_name'), table_name='cc_organization')
    op.drop_table('cc_organization')
    op.drop_table('cc_achievement')
    # ### end Alembic commands ###
