"""add_email_delivery_outbox

Revision ID: 66bb9a5c13af
Revises: 2a0a622797dd
Create Date: 2026-09-18 07:05:42.785119
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66bb9a5c13af'
down_revision: Union[str, Sequence[str], None] = '2a0a622797dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cc_email_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=256), nullable=False, comment='Immutable logical delivery identity; writers must never change or regenerate it on retry.'),
    sa.Column('event_type', sa.String(length=80), server_default='', nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), server_default='', nullable=False, comment='Recipient email snapshot at enqueue time.'),
    sa.Column('recipient_name', sa.String(length=160), server_default='', nullable=False, comment='Recipient name snapshot at enqueue time.'),
    sa.Column('recipient_role', sa.String(length=16), server_default='', nullable=False, comment='Recipient role snapshot at enqueue time, not a live authorization source.'),
    sa.Column('subject', sa.String(length=998), server_default='', nullable=False),
    sa.Column('text_body', sa.Text(), server_default='', nullable=False),
    sa.Column('html_body', sa.Text(), server_default='', nullable=False),
    sa.Column('action_path', sa.String(length=500), server_default='', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True, comment='Provider accepted/sent time; not confirmation of inbox delivery.'),
    sa.Column('provider_message_id', sa.String(length=256), nullable=True),
    sa.Column('last_error_category', sa.String(length=80), server_default='', nullable=False),
    sa.Column('last_error_summary', sa.String(length=1000), server_default='', nullable=False, comment='Redacted diagnostic summary only; sanitize before persistence.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'sending', 'accepted', 'retry', 'blocked', 'failed')", name='ck_cc_email_delivery_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_cc_email_delivery_attempt_count'),
    sa.CheckConstraint('length(event_key) BETWEEN 1 AND 256', name='ck_cc_email_delivery_event_key_length'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', name='uq_cc_email_delivery_event_key')
    )
    op.create_index('ix_cc_email_delivery_email_history', 'cc_email_delivery', ['recipient_email', 'created_at'], unique=False)
    op.create_index('ix_cc_email_delivery_event_type', 'cc_email_delivery', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_cc_email_delivery_provider_id', 'cc_email_delivery', ['provider_message_id'], unique=False)
    op.create_index('ix_cc_email_delivery_recipient_history', 'cc_email_delivery', ['recipient_user_id', 'created_at'], unique=False)
    op.create_index('ix_cc_email_delivery_retry', 'cc_email_delivery', ['status', 'next_attempt_at', 'id'], unique=False)
    op.create_index('ix_cc_email_delivery_scheduled', 'cc_email_delivery', ['status', 'scheduled_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cc_email_delivery_scheduled', table_name='cc_email_delivery')
    op.drop_index('ix_cc_email_delivery_retry', table_name='cc_email_delivery')
    op.drop_index('ix_cc_email_delivery_recipient_history', table_name='cc_email_delivery')
    op.drop_index('ix_cc_email_delivery_provider_id', table_name='cc_email_delivery')
    op.drop_index('ix_cc_email_delivery_event_type', table_name='cc_email_delivery')
    op.drop_index('ix_cc_email_delivery_email_history', table_name='cc_email_delivery')
    op.drop_table('cc_email_delivery')
    # ### end Alembic commands ###
