"""add_user_login_lockout

Revision ID: 72717046a305
Revises: 66bb9a5c13af
Create Date: 2026-09-18 07:15:05.409302
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '72717046a305'
down_revision: Union[str, Sequence[str], None] = '66bb9a5c13af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cc_user', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cc_user', 'locked_until')
    # ### end Alembic commands ###
