"""secure_assessment_upload_certificate_schema

Revision ID: be553432f6e5
Revises: 72717046a305
Create Date: 2026-09-18 16:49:06.696117
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'be553432f6e5'
down_revision: Union[str, Sequence[str], None] = '72717046a305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cc_assessment_attempt', sa.Column('expires_at', sa.DateTime(timezone=True), server_default='1970-01-01 00:00:00+00:00', nullable=False, comment='Authoritative server expiry snapshot set at attempt start. Legacy or omitted values fail closed as already expired.'))
    op.alter_column('cc_certificate', 'verification_code',
               existing_type=sa.VARCHAR(length=64),
               comment='Opaque random public verification token, never a certificate serial. Existing duplicate tokens require remediation before uniqueness is applied.',
               existing_nullable=False)
    op.create_unique_constraint('uq_cc_certificate_verification_code', 'cc_certificate', ['verification_code'])
    op.add_column('cc_learning_resource', sa.Column('file_size_bytes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('cc_learning_resource', sa.Column('content_type', sa.String(length=255), server_default='', nullable=False))
    op.add_column('cc_learning_resource', sa.Column('sha256_digest', sa.String(length=64), server_default='', nullable=False))
    op.add_column('cc_question', sa.Column('competency_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cc_question_competency_id'), 'cc_question', ['competency_id'], unique=False)
    op.create_foreign_key(None, 'cc_question', 'cc_competency', ['competency_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'cc_question', type_='foreignkey')
    op.drop_index(op.f('ix_cc_question_competency_id'), table_name='cc_question')
    op.drop_column('cc_question', 'competency_id')
    op.drop_column('cc_learning_resource', 'sha256_digest')
    op.drop_column('cc_learning_resource', 'content_type')
    op.drop_column('cc_learning_resource', 'file_size_bytes')
    op.drop_constraint('uq_cc_certificate_verification_code', 'cc_certificate', type_='unique')
    op.alter_column('cc_certificate', 'verification_code',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='Opaque random public verification token, never a certificate serial. Existing duplicate tokens require remediation before uniqueness is applied.',
               existing_nullable=False)
    op.drop_column('cc_assessment_attempt', 'expires_at')
    # ### end Alembic commands ###
