"""add_assignment_and_certificate_request_workflows

Revision ID: f1521489770b
Revises: 0a5d11c45adc
Create Date: 2026-09-09 17:19:26.368488
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f1521489770b'
down_revision: Union[str, Sequence[str], None] = '0a5d11c45adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cc_course_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('reference_url', sa.String(length=500), nullable=False),
    sa.Column('assignment_type', sa.String(length=24), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('passing_marks', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allow_late_submission', sa.Boolean(), nullable=False),
    sa.Column('late_penalty_percent', sa.Float(), nullable=False),
    sa.Column('allow_resubmission', sa.Boolean(), nullable=False),
    sa.Column('submission_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'closed', 'archived')", name='ck_cc_assignment_status'),
    sa.CheckConstraint('late_penalty_percent >= 0 AND late_penalty_percent <= 100', name='ck_cc_assignment_late_penalty'),
    sa.CheckConstraint('total_marks >= 0 AND total_marks <= 1000', name='ck_cc_assignment_total_marks'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cc_assignment_course_status', 'cc_course_assignment', ['course_id', 'status'], unique=False)
    op.create_index('ix_cc_assignment_creator_due', 'cc_course_assignment', ['created_by_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_cc_course_assignment_assignment_type'), 'cc_course_assignment', ['assignment_type'], unique=False)
    op.create_index(op.f('ix_cc_course_assignment_course_id'), 'cc_course_assignment', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_course_assignment_status'), 'cc_course_assignment', ['status'], unique=False)
    op.create_table('cc_assignment_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('submission_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('file_size_kb', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marks_awarded', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('graded_by_id', sa.Integer(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'late', 'graded', 'returned')", name='ck_cc_submission_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_cc_submission_attempt_count'),
    sa.CheckConstraint('marks_awarded IS NULL OR marks_awarded >= 0', name='ck_cc_submission_marks_awarded'),
    sa.ForeignKeyConstraint(['assignment_id'], ['cc_course_assignment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graded_by_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainee_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'trainee_id', name='uq_cc_submission_assignment_trainee')
    )
    op.create_index(op.f('ix_cc_assignment_submission_assignment_id'), 'cc_assignment_submission', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_cc_assignment_submission_status'), 'cc_assignment_submission', ['status'], unique=False)
    op.create_index(op.f('ix_cc_assignment_submission_trainee_id'), 'cc_assignment_submission', ['trainee_id'], unique=False)
    op.create_index('ix_cc_submission_assignment_status', 'cc_assignment_submission', ['assignment_id', 'status'], unique=False)
    op.create_index('ix_cc_submission_trainee_status', 'cc_assignment_submission', ['trainee_id', 'status'], unique=False)
    op.create_table('cc_certificate_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('assessments_passed', sa.Integer(), nullable=False),
    sa.Column('assessments_total', sa.Integer(), nullable=False),
    sa.Column('is_eligible_snapshot', sa.Boolean(), nullable=False),
    sa.Column('eligibility_note', sa.Text(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('certificate_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'issued')", name='ck_cc_cert_request_status'),
    sa.CheckConstraint('average_score >= 0 AND average_score <= 100', name='ck_cc_cert_request_score'),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name='ck_cc_cert_request_progress'),
    sa.ForeignKeyConstraint(['certificate_id'], ['cc_certificate.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['cc_course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['cc_enrollment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['cc_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trainee_id'], ['cc_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'trainee_id', name='uq_cc_cert_request_course_trainee')
    )
    op.create_index('ix_cc_cert_request_status_created', 'cc_certificate_request', ['status', 'created_at'], unique=False)
    op.create_index('ix_cc_cert_request_trainee_status', 'cc_certificate_request', ['trainee_id', 'status'], unique=False)
    op.create_index(op.f('ix_cc_certificate_request_certificate_id'), 'cc_certificate_request', ['certificate_id'], unique=False)
    op.create_index(op.f('ix_cc_certificate_request_course_id'), 'cc_certificate_request', ['course_id'], unique=False)
    op.create_index(op.f('ix_cc_certificate_request_enrollment_id'), 'cc_certificate_request', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_cc_certificate_request_status'), 'cc_certificate_request', ['status'], unique=False)
    op.create_index(op.f('ix_cc_certificate_request_trainee_id'), 'cc_certificate_request', ['trainee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cc_certificate_request_trainee_id'), table_name='cc_certificate_request')
    op.drop_index(op.f('ix_cc_certificate_request_status'), table_name='cc_certificate_request')
    op.drop_index(op.f('ix_cc_certificate_request_enrollment_id'), table_name='cc_certificate_request')
    op.drop_index(op.f('ix_cc_certificate_request_course_id'), table_name='cc_certificate_request')
    op.drop_index(op.f('ix_cc_certificate_request_certificate_id'), table_name='cc_certificate_request')
    op.drop_index('ix_cc_cert_request_trainee_status', table_name='cc_certificate_request')
    op.drop_index('ix_cc_cert_request_status_created', table_name='cc_certificate_request')
    op.drop_table('cc_certificate_request')
    op.drop_index('ix_cc_submission_trainee_status', table_name='cc_assignment_submission')
    op.drop_index('ix_cc_submission_assignment_status', table_name='cc_assignment_submission')
    op.drop_index(op.f('ix_cc_assignment_submission_trainee_id'), table_name='cc_assignment_submission')
    op.drop_index(op.f('ix_cc_assignment_submission_status'), table_name='cc_assignment_submission')
    op.drop_index(op.f('ix_cc_assignment_submission_assignment_id'), table_name='cc_assignment_submission')
    op.drop_table('cc_assignment_submission')
    op.drop_index(op.f('ix_cc_course_assignment_status'), table_name='cc_course_assignment')
    op.drop_index(op.f('ix_cc_course_assignment_course_id'), table_name='cc_course_assignment')
    op.drop_index(op.f('ix_cc_course_assignment_assignment_type'), table_name='cc_course_assignment')
    op.drop_index('ix_cc_assignment_creator_due', table_name='cc_course_assignment')
    op.drop_index('ix_cc_assignment_course_status', table_name='cc_course_assignment')
    op.drop_table('cc_course_assignment')
    # ### end Alembic commands ###
